/***
 * Data model for person:
 * id(int) - generated by Neo4j
 * name(string) - unique (will serve as key)
 * file_path(string) - unique()
 *
 */
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import {
  getPerson,
  editPerson,
  deletePerson,
  createPerson,
} from "../connector.js";

function errorHandling(error) {
  console.error("[id]: " + error);
  /* Error handling */
  res.status(500).end();
}

export default function (req, res) {
  const name = req.query.name;
  /* Check ID */
  if (typeof name !== "number") {
    res.status(400).end(); //MALFORMED REQUESTS
  }
  switch (req.method) {
    case "GET":
      return getPerson(name).then((result) => {
        result ? res.status(200).json(result) : res.status(404).end();
      }, errorHandling);
    case "PATCH":
      return editPerson(req.body.person).then((result) => {
        result ? res.status(202).json(result) : res.status(404).end();
      }, errorHandling);
    case "DELETE":
      return deletePerson(name).then((result) => {
        result ? res.status(202).json(result) : res.status(404).end();
      }, errorHandling);
    default:
      console.error(`Not supporting HTTP verb ${req.method}`);
      res.status(405).end();
      break;
  }
}
